# Generated by Django 4.1.6 on 2023-02-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(max_length=50, verbose_name='Название')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ('-titile',),
            },
        ),
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_title', models.CharField(max_length=100, verbose_name='Название модели')),
                ('manufacturer', models.CharField(choices=[('WE', 'WENXUAN'), ('AR', 'Unkown')], default='WENXUAN', max_length=50, verbose_name='Производитель')),
                ('color', models.CharField(max_length=50, verbose_name='цвет')),
                ('stored', models.ManyToManyField(to='main.stock', verbose_name='Местоположение хранения')),
            ],
            options={
                'verbose_name': 'Ручка',
                'verbose_name_plural': 'Ручки',
                'ordering': ('-model_title',),
            },
        ),
    ]
