# Generated by Django 4.1.6 on 2023-02-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='number_of_handles',
            field=models.IntegerField(default=0, verbose_name='Количество ручек'),
        ),
        migrations.AlterField(
            model_name='pen',
            name='model_title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название модели'),
        ),
    ]
